### PR TITLE
Fix proximity read frequency

### PR DESCRIPTION
**Pull request by stonehippo**
Previously, the module used an incorrect register to set the proximity
modulator timing of the chip, rather than the number of proximity
reads per second.

This change updates the getter and setter for frequency to use the
correct proximity rate register, and adds a modulation property to
continue to provide access to that register (though it probably should
be left at the default)

This should address #21

### CODE REVIEW

**Comment by stonehippo** [comment]
@ladyada as requested, here’s the PR for the proximity fix. I’ve left modulation in, even though it’s probably never going to be needed.

**Comment by ladyada** [comment]
oh oh, we see whats up. sorry for the mixup - can you *keep* the 'modulation' setting called 'frequency' but change whatcha have called 'frequency' into `samplerate`?

**Comment by stonehippo** [comment]
Got it. You don't want to redefine `frequency` and break the existing API. ;-)

I've restored `frequency` and changed the measurements per second to `samplerate`.

**Comment by stonehippo** [comment]
Ok, I think this is all set, @ladyada, unless you've got more feedback. Tested on an RP2040 Trinkey and in Blinka on an RPi Zero W.

**Comment by ladyada** [comment]
welll... it didnt work at all before right? so is it really breaking an api if it was already broken :)

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thank u!

@evaherrada this is a breaking change so plz bump major vers :)

**Pull request merged**
